apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: ejercicio10
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 500Mi
    limits.cpu: "1"
    limits.memory: 1Gi